# ansible-playbook ~/ansible/playbooks/add_file_playbook.yaml -i ~/ansible/inventory/hosts.ini
---
- name: creat file on VM
  hosts: admin
  tasks:
    - name: creat_file_example.txt
      file:
        path: ~/ansible/example.txt
        state: touch
