# ansible-playbook ~/ansible/playbooks/add_file_playbook.yaml -i ~/ansible/inventory/hosts.ini
---
- name: creat_file_admin
  hosts: 192.168.56.106
  become: true
  become_user: admin
  tasks:
    - name: Создать файл example.txt
      file:
        path: home/ansible/example.txt
        state: touch


