# ansible-playbook ~/ansible/playbooks/add_file_playbook.yaml -i ~/ansible/inventory/hosts.ini
---
- name: Создание файла на удаленном сервере
  hosts: ваш_хост
  tasks:
    - name: Создать файл example.txt
      file:
        path: /home/ansible/playbooks/example.txt
        state: touch

