# ansible-playbook ~/ansible/playbooks/add_file_playbook.yaml -i ~/ansible/inventory/hosts.ini
---
- name: creat_file_admin
  hosts: all
  remote_user: developer
  tasks:
    - name: create_file_example.txt
      file:
        path: "~/exampl.txt"
        state: touch


