# ansible-playbook ~/ansible/playbooks/add_file_playbook.yaml -i ~/ansible/inventory/hosts.ini
---
- name: creat file on VM
  hosts: 192.168.56.106
  become: yes
  tasks:
    - name: creat_file_example.txt
      file:
        path: home/ansible/playbook/example.txt
        state: touch
