# ansible-playbook ~/ansible/playbooks/add_file_playbook.yaml -i ~/ansible/inventory/hosts.ini
---
- name: creat_file_admin
  hosts: 212.193.56.10
  become_user: admin
  tasks:
    - name: create_file_example.txt
      file:
        path: /ansible/example.txt
        state: touch


