# ansible-playbook ~/ansible/playbooks/add_file_playbook.yaml -i ~/ansible/inventory/hosts.ini
---
- name: creat_file_VM
  hosts: 192.168.56.106
  remote_user: admin
  tasks:
    - name: example.txt
      file:
        path: /home/ansible/example.txt
        state: touch

